query($catergoryName: Mixed) {
  brands: taxonomyContent(where: { column: TITLE, value: $catergoryName }) {
    children {
      id
      title
      children {
        title
        children {
          title
        }
      }
    }
  }
}
