query($userId: Mixed!) {
  messages(
    first: 10000
    where: { column: TO_ID, value: $userId }
    orderBy: { column: CREATED_AT, order: ASC }
  ) {
    data {
      body
      seen_at
      created_at
      sender {
        id
        name
      }
      recipient {
        id
        name
      }
    }
  }
}
