query {
  ad(where: { column: ID, value: 1 }) {
    title
    description
    price
    created_at
    favorited
    user {
      name
      country {
        name
      }
      state {
        name
      }
      reviews {
        data {
          body
          star

          created_at
        }
      }
    }
    comments {
      data {
        body
        user {
          name
        }
        created_at
      }
    }
    taxomomyContents {
      data {
        title
      }
    }
  }
}

#  TODO: Fix the error of not define the datatype of value
