query($operator: SQLOperator, $adID: Mixed) {
  ad(where: { column: ID, operator: $operator, value: $adID }) {
    id
    title
    description
    price
    created_at
    favorite {
      id
      ad {
        id
      }
    }
    user {
      id
      attachments {
        data {
          id
          path
        }
      }
      id
      name
      phone_no
      country {
        id
        name
      }
      state {
        id
        name
      }
      reviews {
        data {
          id
          body
          star

          created_at
          reviewer {
            id
            attachments {
              data {
                id
                path
              }
            }
            name
          }
        }
      }
    }
    comments {
      data {
        id
        body
        user {
          id
          name
          attachments {
            data {
              id
              path
            }
          }
        }
        created_at
      }
    }
    taxonomyContents {
      data {
        id
        title
      }
    }
    attachments {
      data {
        id
        path
        attachable_id
        attachable_type
        type
        disk_name
        file_name
        thumbnail
      }
    }
  }
}
