query($operator: SQLOperator, $valueName: Mixed, $itemsNumber: Int!) {
  ads(
    orderBy: { column: ID, order: DESC }
    first: $itemsNumber
    taxonomyContents: { column: TITLE, operator: $operator, value: $valueName }
  ) {
    data {
      id
      title
      description
      price
      sku
      negotiable
      created_at
      taxonomyContents {
        data {
          id
          title
        }
      }
      user {
        id
        name
        country {
          id
          code
          name
          phone_code
        }
        state {
          id
          name
        }
      }
      attachments {
        data {
          id
          path
          attachable_id
          attachable_type
          type
          disk_name
          file_name
          thumbnail
        }
      }
      comments {
        data {
          id
          body
          user {
            id
            name
          }
        }
      }
      # reports {
      #   data {
      #     id
      #     name
      #     type
      #     created_at
      #   }
      # }
    }
  }
}
