query($operator: SQLOperator, $valueName: Mixed) {
  ads(
    orderBy: { column: ID, order: DESC }
    first: 100
    taxonomyContents: { column: TITLE, operator: $operator, value: $valueName }
  ) {
    data {
      id
      title
      description
      price
      sku
      negotiable
      created_at
      taxonomyContents {
        data {
          title
        }
      }
      user {
        name
        country {
          code
          name
          phone_code
        }
        state {
          name
        }
      }
      attachments {
        data {
          path
          attachable_id
          attachable_type
          type
          disk_name
          file_name
          thumbnail
        }
      }
      comments {
        data {
          body
          user {
            name
          }
        }
      }
      reports {
        data {
          name
          type
          created_at
        }
      }
    }
  }
}
