query($operator: SQLOperator, $valueName: Mixed) {
  ads(
    taxonomyContents: { column: TITLE, operator: $operator, value: $valueName }
  ) {
    data {
      id
      title
      description
      price
      sku
      negotiable
      created_at
      taxonomyContents {
        data {
          title
        }
      }
      user {
        name
        country {
          code
          name
          phone_code
        }
        state {
          name
        }
      }
      comments {
        data {
          body
          user {
            name
          }
        }
      }
      reports {
        data {
          name
          type
          created_at
        }
      }
    }
  }
}
