query($operator: SQLOperator, $user_id: Mixed, $ad_id: Mixed) {
  favorite(
    where: {
      AND: [
        { column: FAVORITEABLE_ID, operator: $operator, value: $ad_id }
        { column: USER_ID, operator: $operator, value: $user_id }
      ]
    }
  ) {
    id
    ad {
      id
      title
    }
  }
}
