query($userId: Mixed!) {
  interacted_users: messages(
    where: {
      OR: [
        { column: FROM_ID, value: $userId }
        { column: TO_ID, value: $userId }
      ]
    }
    orderBy: { column: CREATED_AT, order: ASC }
  ) {
    data {
      sender {
        id
        name
      }
    }
  }
}
