query($id: ID!) {
  user(id: $id) {
    id
    name
    gender
    phone_no
    email
    created_at
    email_verified_at
    phone_verified_at
    deleted_at
    remember_token
    updated_at
    country {
      id

      name
      code
      phone_code
    }

    state {
      id

      name
    }

    ads {
      data {
        id
        title
        description
        price
        sku
        negotiable
        # favorited
        created_at
        user {
          id
          name
          country {
            id

            code
            name
            phone_code
          }
          state {
            id

            name
          }
        }
        comments {
          data {
            id
            body
            user {
              name
            }
          }
        }
        reports {
          data {
            id
            name
            type
            created_at
          }
        }
        taxonomyContents {
          data {
            id
            title
          }
        }
        attachments {
          data {
            id
            path
            attachable_id
            attachable_type
            type
            disk_name
            file_name
            thumbnail
          }
        }
      }
    }

    reviews {
      data {
        reviewer {
          id
          name
        }
        body
        star
        reports {
          data {
            id
            name
            type
          }
        }
      }
    }

    comments {
      data {
        body
        created_at
        user {
          name
        }
        ad {
          title
        }
      }
    }
  }
}
